SiteEmprestimos/Models/EmprestimosModel.cs
using System.ComponentModel.DataAnnotations;

namespace SiteEmprestimos.Models
{
    public class EmprestimosModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório!")]
        [StringLength(100, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
        public string Fornecedor { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório!")]
        [StringLength(100, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
        public string Recebedor { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório!")]
        [StringLength(100, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
        public string LivroEmprestado { get; set; }
        public DateTime DataUltimaAtualizacao { get; set; } = DateTime.Now;
    }
}

SiteEmprestimos/Models/ErrorViewModel.cs
namespace SiteEmprestimos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SiteEmprestimos/Controllers/EmprestimoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SiteEmprestimos.Data;
using SiteEmprestimos.Models;

namespace SiteEmprestimos.Controllers
{
    public class EmprestimoController : Controller
    {
		private readonly ApplicationDbContext _db;
		public EmprestimoController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
			IEnumerable<EmprestimosModel> emprestimos = _db.Emprestimo;
            
            return View(emprestimos);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(EmprestimosModel emprestimos)
        {
            if(ModelState.IsValid)
            {
                _db.Emprestimo.Add(emprestimos);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Cadastro realizado com sucesso";

                return RedirectToAction("Index");
            }
            
            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }

            EmprestimosModel emprestimo = _db.Emprestimo.FirstOrDefault(x => x.Id == id);  

            if(emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        [HttpPost]
        public IActionResult Editar(EmprestimosModel emprestimo) 
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimo.Update(emprestimo);
                _db.SaveChanges();

				TempData["MensagemSucesso"] = "Edição realizada com sucesso";

				return RedirectToAction("Index");
			}

            return View(emprestimo);
        }

        [HttpGet]
        public IActionResult Excluir(int? id) 
        {
			if (id == null || id == 0)
			{
				return NotFound();
			}

            EmprestimosModel emprestimo = _db.Emprestimo.FirstOrDefault(emp => emp.Id == id);

            if(emprestimo == null)
            {
                return NotFound();
            }

			return View(emprestimo);
        }

        [HttpPost]
        public IActionResult Excluir(EmprestimosModel emprestimo)
        {
            if(emprestimo == null) 
            { 
                return NotFound(); 
            } 

            _db.Emprestimo.Remove(emprestimo);
            _db.SaveChanges();

			TempData["MensagemSucesso"] = "Remoção realizada com sucesso";

			return RedirectToAction("Index");
        }
	}
}

SiteEmprestimos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SiteEmprestimos.Models;
using System.Diagnostics;

namespace SiteEmprestimos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            bool isDarkMode = false;
            if (Request.Cookies.TryGetValue("darkMode", out var darkModeValue))
            {
                bool.TryParse(darkModeValue, out isDarkMode);
            }

            ViewBag.isDarkMode = isDarkMode;
            
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SiteEmprestimos/Views/Emprestimo/Cadastrar.cshtml
@model EmprestimosModel

@{
    ViewData["Title"] = "Cadastrar Empréstimo";
}

<div class="container p-5 rounded-5">
    <div class="mb-5 text center">
        <h1>Cadastro de Empréstimos</h1>
    </div>

<form method="post" asp-controller="Emprestimo" asp-action="Cadastrar">
    <div class="mb-3">
        <label for="Recebedor" class="form-label">Recebedor:</label>
        <input type="text" class="form-control" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o Livro?">
        <span class="text-danger" asp-validation-for="Recebedor"></span>
    </div>

    <div class="mb-3">
        <label for="Fornecedor" class="form-label">Fornecedor:</label>
        <input type="text" class="form-control" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando o Livro?">
        <span class="text-danger" asp-validation-for="Fornecedor"></span>
    </div>

    <div class="mb-3">
        <label for="Livro" class="form-label">Livro</label>
        <input type="text" class="form-control" asp-for="LivroEmprestado" id="Livro" placeholder="Nome do Livro que está sendo emprestado">
        <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
    </div>

    <div class="d-flex gap-5 mt-5">
        <button type="submit" class="btn btn-success w-50">Adicionar</button>
        <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
    </div>

</form>
</div>

SiteEmprestimos/Views/Emprestimo/Editar.cshtml
@model EmprestimosModel

@{
    ViewData["Title"] = "Editar Empréstimo";
}

<div class="container p-5 rounded-5">
    <div class="mb-5 text center">
        <h1>Edição de Empréstimos</h1>
    </div>

<form method="post" asp-controller="Emprestimo" asp-action="Editar">

    <input type="hidden" asp-for="Id" />

    <div class="mb-3">
        <label for="Recebedor" class="form-label">Recebedor:</label>
        <input type="text" class="form-control" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o Livro?">
        <span class="text-danger" asp-validation-for="Recebedor"></span>
    </div>

    <div class="mb-3">
        <label for="Fornecedor" class="form-label">Fornecedor:</label>
        <input type="text" class="form-control" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando o Livro?">
        <span class="text-danger" asp-validation-for="Fornecedor"></span>
    </div>

    <div class="mb-3">
        <label for="Livro" class="form-label">Livro</label>
        <input type="text" class="form-control" asp-for="LivroEmprestado" id="Livro" placeholder="Nome do Livro que está sendo emprestado">
        <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
    </div>

    <div class="d-flex gap-5 mt-5">
        <button type="submit" class="btn btn-success w-50">Editar</button>
        <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
    </div>

</form>
</div>

SiteEmprestimos/Views/Emprestimo/Excluir.cshtml
@model EmprestimosModel

@{
    ViewData["Title"] = "Excluir Empréstimo";
}

<div class="container p-5 rounded-5">
    <div class="mb-5 text center">
        <h1>Excluir Empréstimo</h1>
    </div>

    <form method="post" asp-controller="Emprestimo" asp-action="Excluir">

        <input type="hidden" asp-for="Id" />

        <h2>Tem certeza que deseja excluir?</h2>

        <div class="mb-3">
            <label for="Recebedor" class="form-label">Recebedor:</label>
            <input type="text" class="form-control" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o Livro?" disabled>
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-3">
            <label for="Fornecedor" class="form-label">Fornecedor:</label>
            <input type="text" class="form-control" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando o Livro?" disabled>
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label">Livro</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" id="Livro" placeholder="Nome do Livro que está sendo emprestado" disabled>
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>

    </form>
</div>

SiteEmprestimos/Views/Emprestimo/Index.cshtml
@model IEnumerable<EmprestimosModel>

<div class="container">
	<div class="d-flex justify-content-between align-items-center mb-5">
		<h1>Empréstimos</h1>
		<a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Cadastrar"><i class="bi bi-file-earmark-plus mx-1"></i>Cadastrar novo Empréstimo</a>
	</div>

	@if (TempData["MensagemSucesso"] != null)
	{
		<div class="alert alert-success text-light" role="alert">
			@TempData["MensagemSucesso"]
		</div>
	}

<table id="Emprestimos" class="table table-hover mt-4">
	<thead>
		<tr>
			<th scope="col">Recebedor</th>
			<th scope="col">Fornecedor</th>
			<th scope="col">Livro</th>
			<th scope="col">Ultima Atualização</th>
			<th></th>
		</tr>
	</thead>
	<tbody>

		@if (Model != null)
		{
			@foreach (var emprestimo in Model)
			{
				<tr>
					<th scope="row">@emprestimo.Recebedor</th>
					<td>@emprestimo.Fornecedor</td>
					<td>@emprestimo.LivroEmprestado</td>
					<td>@emprestimo.DataUltimaAtualizacao</td>
					<td class="text-right">
							<a asp-controller="Emprestimo" asp-action="Editar" asp-route-id="@emprestimo.Id" class="btn btn-warning mx-2"><i class="bi bi-pencil-square mx-1"></i>Editar</a>
							<a asp-controller="Emprestimo" asp-action="Excluir" asp-route-id="@emprestimo.Id" class="btn btn-danger mx-2"><i class="bi bi-trash3 mx-1"></i>Excluir</a>
					</td>
				</tr>
			}
		}
	</tbody>
</table>
</div>

SiteEmprestimos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Books Watch</h1>
    <h4>Site de Empréstimos de Livros Online</h4>

    <p>Abra um livro, deixe-se levar. Um novo mundo você vai encontrar!</p>

    <div>
        <img src="/img/livroSite.png"/>
    </div>

</div>

SiteEmprestimos/Views/Shared/_Layout.cshtml
@{
    bool isDarkMode = ViewBag.IsDarkMode ?? false;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BooksWatch</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/flatly.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SiteEmprestimos.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
</head>
<body class="@(isDarkMode ? "dark-mode" : "")">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-book-half mx-1"></i>Books Watch</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house mx-2"></i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Emprestimo" asp-action="Index"><i class="bi bi-journals mx-2"></i>Empréstimos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Home" asp-action="Privacy"><i class="bi bi-shield mx-2"></i>Privacidade</a>
                        </li>
                    </ul>
                    <div class="toggle-mode">
                        <input type="checkbox" id="mode-switch" class="toggle-checkbox">
                        <label for="mode-switch" class="toggle-label">
                            <i class="bi bi-brightness-high-fill"></i> <!-- Ícone de lua -->
                            <i class="bi bi-moon-fill"></i> <!-- Ícone de sol -->
                        </label>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var modeSwitch = document.getElementById('mode-switch');
            modeSwitch.addEventListener('change', function () {
                document.body.classList.toggle('dark-mode');
                var isDarkMode = document.body.classList.contains('dark-mode');

                document.cookie = "darkMode" + isDarkMode + "; expires=Sun, 1 Jan 2023 00:00:00 UTC; path=/";
            });
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>